# Generated by Django 5.2.1 on 2025-06-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='image3',
        ),
        migrations.AddField(
            model_name='subproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
