# Generated by Django 5.2.3 on 2025-07-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orderproduct_options_remove_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/subproduct_images/'),
        ),
    ]
